# ===========================================
# STUDENT TODO: Complete this Docker Compose file
# ===========================================

version: '3.8'

services:
  # 1. Frontend service
  frontend:
    image: ducknolife/frontend:latest
    ports:
      - "3000:3000"
    environment:
      # Pass the backend URL to your React app to fetch the correct address when running Docker.
      - REACT_APP_API_URL=https://backend-latest-g3.onrender.com/
    depends_on:
      - backend

  # 2. Backend service
  backend:
    image: ducknolife/backend:latest
    ports:
      - "8080:8080"
    environment:
      # Environment variables related to database connection
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tododb
      - DB_USER=postgres
      - DB_PASSWORD=secret_password
    depends_on:
      postgres:
        # It is mandatory to wait for Postgres to pass the healthcheck before starting the backend.
        condition: service_healthy
    healthcheck:
      # Check if the backend is ready to receive requests.
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Postgres service
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      # Initialize default information for the database.
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
    volumes:
      # Store data permanently 
      - postgres_data:/var/lib/postgresql/data
      # Mount the script to automatically run when the database is first initialized.
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

# 4. Define named volumes
volumes:
  postgres_data: